from typing import ClassVar

__version__: str

class ValidationError(ValueError): ...
class NotConnectedError(ConnectionError): ...
class DiscoveryError(ConnectionError): ...

class _PybindEnum:
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

class ForceUnit(_PybindEnum):
    __members__: ClassVar[dict[str, ForceUnit]]
    UNKNOWN: ClassVar[ForceUnit]
    POUND_FORCE: ClassVar[ForceUnit]
    NEWTON: ClassVar[ForceUnit]
    KILO_POUND_FORCE: ClassVar[ForceUnit]
    KILO_NEWTON: ClassVar[ForceUnit]
    KILOGRAM_FORCE: ClassVar[ForceUnit]

    def __init__(self, value: int | ForceUnit) -> None: ...

class TorqueUnit(_PybindEnum):
    __members__: ClassVar[dict[str, TorqueUnit]]
    UNKNOWN: ClassVar[TorqueUnit]
    POUND_FORCE_INCH: ClassVar[TorqueUnit]
    POUND_FORCE_FOOT: ClassVar[TorqueUnit]
    NEWTON_METER: ClassVar[TorqueUnit]
    NEWTON_MILLIMETER: ClassVar[TorqueUnit]
    KILOGRAM_FORCE_CENTIMETER: ClassVar[TorqueUnit]
    KILO_NEWTON_METER: ClassVar[TorqueUnit]

    def __init__(self, value: int | TorqueUnit) -> None: ...

class CalibrationSource(_PybindEnum):
    __members__: ClassVar[dict[str, CalibrationSource]]
    SENSOR: ClassVar[CalibrationSource]
    OVERRIDE: ClassVar[CalibrationSource]

    def __init__(self, value: int | CalibrationSource) -> None: ...

class RecoveryPolicy(_PybindEnum):
    __members__: ClassVar[dict[str, RecoveryPolicy]]
    RECONNECT: ClassVar[RecoveryPolicy]
    FAIL_STOP: ClassVar[RecoveryPolicy]

    def __init__(self, value: int | RecoveryPolicy) -> None: ...

class ClientState(_PybindEnum):
    __members__: ClassVar[dict[str, ClientState]]
    STOPPED: ClassVar[ClientState]
    CONNECTING: ClassVar[ClientState]
    STREAMING: ClassVar[ClientState]
    BACKOFF: ClassVar[ClientState]
    FAULTED: ClassVar[ClientState]

    def __init__(self, value: int | ClientState) -> None: ...

class FaultCode(_PybindEnum):
    __members__: ClassVar[dict[str, FaultCode]]
    NONE: ClassVar[FaultCode]
    SENSOR_CONFIGURATION: ClassVar[FaultCode]
    TIMEOUT: ClassVar[FaultCode]
    SOCKET: ClassVar[FaultCode]
    SERIOUS_STATUS: ClassVar[FaultCode]
    FT_STALL: ClassVar[FaultCode]
    FT_BACKWARD: ClassVar[FaultCode]
    MALFORMED_STORM: ClassVar[FaultCode]
    CALLBACK: ClassVar[FaultCode]

    def __init__(self, value: int | FaultCode) -> None: ...

class StatusSeverity(_PybindEnum):
    __members__: ClassVar[dict[str, StatusSeverity]]
    OK: ClassVar[StatusSeverity]
    WARN: ClassVar[StatusSeverity]
    ERROR: ClassVar[StatusSeverity]

    def __init__(self, value: int | StatusSeverity) -> None: ...

class Calibration:
    counts_per_force_unit: float
    counts_per_torque_unit: float
    force_unit: ForceUnit
    torque_unit: TorqueUnit

    def __init__(self) -> None: ...

class SensorConfiguration:
    product_name: str
    calibration: Calibration
    source: CalibrationSource
    revision: int

    def __init__(self) -> None: ...

class Config:
    sensor_host: str
    rdt_port: int
    http_port: int
    receive_timeout: float
    configuration_connect_timeout: float
    configuration_timeout: float
    reconnect_initial_delay: float
    reconnect_max_delay: float
    sample_rate_limit_hz: float
    deliver_samples_with_error_status: bool
    recovery_policy: RecoveryPolicy
    calibration_override: Calibration | None

    def __init__(self) -> None: ...

class Sample:
    def __init__(self) -> None: ...
    @property
    def rdt_sequence(self) -> int: ...
    @property
    def ft_sequence(self) -> int: ...
    @property
    def status(self) -> int: ...
    @property
    def raw_wrench(self) -> list[int]: ...
    @property
    def force(self) -> list[float]: ...
    @property
    def torque(self) -> list[float]: ...
    @property
    def force_unit(self) -> ForceUnit: ...
    @property
    def torque_unit(self) -> TorqueUnit: ...
    @property
    def configuration_revision(self) -> int: ...
    @property
    def received_at_ns(self) -> int: ...

class Health:
    def __init__(self) -> None: ...
    @property
    def state(self) -> ClientState: ...
    @property
    def fault_code(self) -> FaultCode: ...
    @property
    def sensor_host(self) -> str: ...
    @property
    def rdt_port(self) -> int: ...
    @property
    def sensor_configuration(self) -> SensorConfiguration | None: ...
    @property
    def last_rdt_sequence(self) -> int | None: ...
    @property
    def last_ft_sequence(self) -> int | None: ...
    @property
    def last_status(self) -> int: ...
    @property
    def receive_rate_hz(self) -> float: ...
    @property
    def delivery_rate_hz(self) -> float: ...
    @property
    def received_count(self) -> int: ...
    @property
    def delivered_count(self) -> int: ...
    @property
    def rate_limited_count(self) -> int: ...
    @property
    def device_error_count(self) -> int: ...
    @property
    def warning_count(self) -> int: ...
    @property
    def lost_count(self) -> int: ...
    @property
    def duplicate_count(self) -> int: ...
    @property
    def out_of_order_count(self) -> int: ...
    @property
    def malformed_count(self) -> int: ...
    @property
    def reconnect_count(self) -> int: ...
    @property
    def timeout_count(self) -> int: ...
    @property
    def callback_error_count(self) -> int: ...
    @property
    def ft_stall_count(self) -> int: ...
    @property
    def ft_backward_count(self) -> int: ...
    @property
    def ft_restart_count(self) -> int: ...
    @property
    def calibration_change_count(self) -> int: ...
    @property
    def last_record_age(self) -> float | None: ...
    @property
    def last_error(self) -> str: ...
    @property
    def last_ft_progress(self) -> str: ...

class ReadStatus(_PybindEnum):
    __members__: ClassVar[dict[str, ReadStatus]]
    SAMPLE: ClassVar[ReadStatus]
    TIMEOUT: ClassVar[ReadStatus]
    CLOSED: ClassVar[ReadStatus]

    def __init__(self, value: int | ReadStatus) -> None: ...

class ReadResult:
    def __init__(self) -> None: ...
    @property
    def status(self) -> ReadStatus: ...
    @property
    def sample(self) -> Sample | None: ...

class NativeClient:
    def __init__(self, config: Config, queue_size: int) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def bias(self) -> None: ...
    def wait_for_first_sample(self, timeout: float) -> bool: ...
    def read(self, timeout: float | None = None) -> ReadResult: ...
    def latest_sample(self) -> Sample | None: ...
    def health(self) -> Health: ...
    def faulted(self) -> bool: ...
    def fault_code(self) -> FaultCode: ...
    def queue_dropped_count(self) -> int: ...
